### ISSUE TITLE
Problem starting a new project using cookiecutter (probably something wrong with the template?)

### ISSUE THREAD

**Issue by nassosoassos** [georgepar/slp#20]
I've tried to start a new project based on slp, following the guidelines in the README and I'm getting the following? Any ideas?

% cookiecutter gh:georgepar/cookiecutter-pytorch-slp
author_name [Giorgos Paraskevopoulos]: Nassos Katsamanis
author_email [georgepar.91@gmail.com]: myemail
project_name [ml_project]: Test_slp
project_description [My cool algorithm...]: This is indeed about a cool method.
project_repo [https://github.com/georgepar/ml_project]: https://github.com/nassosoassos/test-slp
project_license [MIT]:
[Errno 62] Too many levels of symbolic links: 'README.md'

**Comment by georgepar** [comment]
Fixed :)
