### ISSUE TITLE
Failure to install library (ERROR: No matching distribution found for torchvision<0.9.0,>=0.8.2)

### ISSUE THREAD

**Issue by Poulinakis-Konstantinos** [georgepar/slp#42]
I created a fresh conda environment with python-3.8.15. I immediately tried to install slp via
`pip install slp==1.1.6`. I am on Windows 10. Installation failed with the following output.
(I have encountered similar error on Linux platform as well, I may open a separate issue for that).

**Terminal output :** 

Collecting slp==1.1.6
  Using cached slp-1.1.6-py3-none-any.whl (70 kB)
Collecting pytorch-lightning<2.0.0,>=1.2.0
  Using cached pytorch_lightning-1.8.3.post1-py3-none-any.whl (798 kB)
Collecting aiohttp<4.0.0,>=3.7.4
  Using cached aiohttp-3.8.3-cp38-cp38-win_amd64.whl (324 kB)
Collecting matplotlib<4.0.0,>=3.3.4
  Downloading matplotlib-3.6.2-cp38-cp38-win_amd64.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 7.7 MB/s eta 0:00:00
Collecting scikit-learn<0.25.0,>=0.24.1
  Using cached scikit_learn-0.24.2-cp38-cp38-win_amd64.whl (6.9 MB)
Collecting pytorch-lightning-bolts<0.4.0,>=0.3.0
  Using cached pytorch_lightning_bolts-0.3.2.post1-py3-none-any.whl (252 kB)
Collecting toml<0.11.0,>=0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting scipy<2.0.0,>=1.6.1
  Downloading scipy-1.9.3-cp38-cp38-win_amd64.whl (39.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.8/39.8 MB 8.3 MB/s eta 0:00:00
Collecting transformers==4.3.0
  Using cached transformers-4.3.0-py3-none-any.whl (1.8 MB)
ERROR: Could not find a version that satisfies the requirement torchvision<0.9.0,>=0.8.2 (from slp) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0)
ERROR: No matching distribution found for torchvision<0.9.0,>=0.8.2

**UPDATE**
I attempted to first install torch via `pip install torch==1.7`. After successful installation of torch-1.7 I rerun 
`pip install slp==1.1.6` . The output is 

pip install slp==1.1.6 
Collecting slp==1.1.6
  Using cached slp-1.1.6-py3-none-any.whl (70 kB)
Collecting matplotlib<4.0.0,>=3.3.4
  Using cached matplotlib-3.6.2-cp38-cp38-win_amd64.whl (7.2 MB)
Collecting pytorch-lightning-bolts<0.4.0,>=0.3.0
  Using cached pytorch_lightning_bolts-0.3.2.post1-py3-none-any.whl (252 kB)
Collecting scipy<2.0.0,>=1.6.1
  Using cached scipy-1.9.3-cp38-cp38-win_amd64.whl (39.8 MB)
ERROR: Could not find a version that satisfies the requirement mike<0.7.0,>=0.6.0 (from slp) (from versions: 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2)
ERROR: No matching distribution found for mike<0.7.0,>=0.6.0

**UPDATE**
Finally I attempted to clone the repo and run poetry install. The error message is :

Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because slp depends on mike (^1.1.2) which doesn't match any versions, version solving failed.

**Comment by georgepar** [comment]
Probably the last commit is responsible 

https://github.com/georgepar/slp/commit/e4987310ed277abdec19462bdd749e2e7a000bec

can you try without this?

**Comment by Poulinakis-Konstantinos** [comment]
This indeed solves the installation problem. 
Thanks
